/*
 * Tallytop, a desktop app aiming to give you a snappier Discord Experience
 * Copyright (c) 2023 Vendicated and Vencord contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import "./themedSplash";
import "./ipcCommands";
import "./appBadge";
import "./fixes";
import "./arrpc";
import "__patches__"; // auto generated by the build script

export * as Components from "./components";

import SettingsUi from "./components/settings/Settings";
import { TallytopLogger } from "./logger";
import { Settings } from "./settings";
export { Settings };

import type SettingsPlugin from "@vencord/types/plugins/_core/settings";

TallytopLogger.log("read if cute :3");
TallytopLogger.log("Tallytop v" + TallytopNative.app.getVersion());

// TODO
const customSettingsSections = (Vencord.Plugins.plugins.Settings as typeof SettingsPlugin).customSections;

customSettingsSections.push(() => ({
    section: "Tallytop",
    label: "Tallytop Settings",
    element: SettingsUi,
    className: "vc-tallytop-settings"
}));

// TODO: remove this legacy workaround once some time has passed
if (!Vencord.Api.Styles.vencordRootNode) {
    const style = document.createElement("style");
    style.id = "vesktop-css-core";

    TallytopNative.app.getRendererCss().then(css => (style.textContent = css));

    document.addEventListener("DOMContentLoaded", () => document.documentElement.append(style), { once: true });
}
